<?php
if (!isset($active_nav)) {
    $active_nav = 'home';
}

$nav = [
    'home' => ['url' => '/admin', 'text' => 'Home'],
    'incoming' => ['url' => '/admin/incoming', 'text' => 'Incoming Entries'],
    'approved' => ['url' => '/admin/approved', 'text' => 'Approved Entries'],
    'winners' => ['url' => '/admin/winners', 'text' => 'Winning Entries'],
];
?>


<div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#"><?= $this->escape($page->app_title) ?></a>
          <div class="nav-collapse collapse">
            <ul class="nav">
            <?php foreach ($nav as $key => $link): ?>
              <li <?= ($active_nav == $key) ? 'class="active"' : '' ?>><a href="<?= $link['url'] ?>"><?= $link['text'] ?></a></li>
            <?php endforeach; ?>

                <li class="pull-right"><a href="/logout">logout</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>