<?php
$this->header();
$active_nav = 'incoming';
include( __DIR__ . '/_nav.phtml');
use Socon\Model\Entry;
?>


    <div class="container">
        <div class="pull-right">
            <input type="button" id="approve-all" class="btn btn-success" value="Approve All"
                   title="Approve all entries." />
        </div>
        <h1>Incoming Entries</h1>

<?php
    if ($entries):
        $i = 0;
?>
        <div class="row-fluid" id="incomingList">
        <?php
        /** @var \Socon\Model\Entry $entry */
        foreach ($entries as $entry):
            $i++;
            if (!$entry) continue;

        ?>
                <div class="span4 well well-small entry-card"
                     data-status="<?= Entry::STATUS_APPROVED ?>" data-id="<?= $entry->getId() ?>"
                     data-prev-status="<?= $entry->getStatus() ?>">

                    <div class="span2">
                        <?php if ($entry->getUserImage()): ?>
                            <img src="<?= $entry->getUserImage() ?>" class="img-responsive" />
                        <?php endif; ?>
                    </div>

                    <div class="span9">


                        <b class="icon icon-<?=$entry->getSource() ?>">
                            <a href="<?= $entry->getUserUrl() ?>"><?=
                                $this->escape($entry->getUserName())
                                ?></a>
                        </b>

                        <p><?= $this->escape($entry->getContent()) ?></p>
                        <?php if ($image = $this->EntryImageUrl($entry, $container_url)): ?>
                            <div class="span9 twimage">
                                <img class="img-responsive" src="<?= $image ?>"
                                     alt="" />
                            </div>
                        <?php endif; ?>
                    </div>

                    <div class="btn-block clearfix">
                        <a target="_blank" href="<?= $entry->getUrl() ?>" class="btn btn-small"><i
                                class="icon icon-eye-open"></i></a>
                        <input type="button" class="btn btn-primary" value="Approve" title="Move to approved queue."
                               data-status="<?= Entry::STATUS_APPROVED ?>" data-id="<?= $entry->getId() ?>"
                               data-prev-status="<?= $entry->getStatus() ?>" />
                        <input type="button" class="btn btn-danger" value="Deny" title="Move to denied queue."
                               data-status="<?= Entry::STATUS_DENIED ?>" data-id="<?= $entry->getId() ?>"
                               data-prev-status="<?= $entry->getStatus() ?>" />
                    </div>

                </div><!-- .well -->
        <?php endforeach; ?>
        </div>
        <?php if (0 == $i): ?>
            <p class="text-warning">None found.</p>
        <?php endif; ?>
    <?php endif; ?>

        <div class="row">
            <p><?= date('Y-m-d h:ia') ?></p>
        </div>
    </div> <!-- /container -->
<?php
$this->footer();